package uk.co.zlurgg.mybookshelf.di

import android.content.Context
import kotlin.reflect.KClass
import kotlin.reflect.full.primaryConstructor
import kotlin.test.fail
import org.junit.Test
import org.koin.core.annotation.KoinExperimentalAPI
import org.koin.core.annotation.KoinInternalApi
import org.koin.core.module.Module
import org.koin.test.verify.definition
import org.koin.test.verify.verify
import uk.co.zlurgg.mybookshelf.bookdetail.presentation.BookDetailViewModel
import uk.co.zlurgg.mybookshelf.bookshelf.presentation.BookshelfViewModel

/**
 * Two layers of static guard against Koin wiring regressions that would
 * crash the app at launch but pass all unit tests (which construct classes
 * directly, bypassing Koin).
 *
 * Source of truth for the module graph: `MyBookshelfApplication.startKoin { ... }`
 * + `AppModule.appModule.includes(...)` + `DebugModuleProvider.getModules()`.
 * Unit tests run against the `debug` variant, so `DebugModuleProvider` resolves
 * to the debug source set's version and its modules are verified too.
 */
@OptIn(KoinInternalApi::class, KoinExperimentalAPI::class)
class KoinModuleVerifyTest {

    /**
     * Layer 1 — Koin's official `verify()`. Catches missing `bind` calls,
     * unbound generics, typos in qualifiers, etc. Does NOT catch
     * `singleOf(::Foo)`-with-defaults: `verify()` honors `KParameter.isOptional`
     * and skips defaulted params. Layer 2 handles that.
     */
    @Test
    fun `appModule and all included modules verify against the merged graph`() {
        appModule.verify(
            extraTypes = EXTRA_TYPES,
            injections = PARAMETERIZED_INJECTIONS,
        )
    }

    /**
     * Layer 2 — strict reflection check. Walks every BeanDefinition whose
     * definition lambda was auto-generated by `singleOf` / `viewModelOf` /
     * `factoryOf` (those lambdas call `get()` for every constructor parameter,
     * including ones with Kotlin defaults), and asserts every parameter is
     * either provided by the merged graph, in [EXTRA_TYPES], or in
     * [PARAMETERIZED_INJECTIONS]. User-provided `single { ... }` lambdas are
     * skipped — they control which params to resolve.
     *
     * Why this exists: on 2026-05-26 the app crashed on cold launch after
     * `singleOf(::GoogleBooksApiService)` and `singleOf(::GoogleBooksRemoteBookDataSource)`
     * were used against constructors carrying a `apiKeyProvider: () -> String = { ... }`
     * test seam. `singleOf` ignores Kotlin defaults and tries to resolve
     * `Function0<String>` from the graph — boom. All 685 unit tests passed;
     * only an actual launch surfaced it. See commit 68c6c617.
     *
     * If you need a default-parameter test seam on a class, register it via
     * `single { Foo(arg = get()) }` (NOT `singleOf(::Foo)`) so the Kotlin
     * default applies. That switches the definition to a user-provided
     * lambda which this check correctly skips.
     */
    @Test
    fun `every constructor parameter resolves from the graph (catches singleOf-with-defaults regressions)`() {
        val modules = flatten(appModule)
        val providedTypes = modules
            .flatMap { it.mappings.values }
            .flatMap { factory ->
                val bd = factory.beanDefinition
                listOf(bd.primaryType) + bd.secondaryTypes
            }
            .toSet()

        val failures = mutableListOf<String>()

        // Only auto-generated singleOf/viewModelOf/factoryOf lambdas are checked
        // strictly — user-provided `single { ... }` lambdas decide for themselves
        // which constructor parameters to resolve via `get()` vs. compute inline.
        val seen = mutableSetOf<Any>()
        modules.flatMap { it.mappings.values }.forEach { factory ->
            if (!seen.add(factory)) return@forEach // singleOf+bind registers twice
            val cls = factory.beanDefinition.primaryType
            if (!isAutoGeneratedKoinLambda(factory.beanDefinition.definition)) return@forEach
            val ctor = cls.primaryConstructor ?: return@forEach
            val injected = PER_CLASS_INJECTIONS[cls]?.toMutableList() ?: mutableListOf()

            ctor.parameters.forEach inner@{ param ->
                val paramCls = (param.type.classifier as? KClass<*>) ?: return@inner
                if (paramCls in EXTRA_TYPES_SET) return@inner
                if (paramCls in providedTypes) return@inner
                val matched = injected.indexOfFirst { it == paramCls }
                if (matched >= 0) {
                    injected.removeAt(matched)
                    return@inner
                }
                failures += "${cls.qualifiedName}.${param.name}: " +
                    "${paramCls.qualifiedName} unresolvable from the Koin graph"
            }
        }

        if (failures.isNotEmpty()) {
            fail(
                buildString {
                    appendLine(
                        "Found ${failures.size} constructor parameter(s) in singleOf/viewModelOf/factoryOf"
                    )
                    appendLine(
                        "definitions with no resolvable Koin definition. `singleOf` calls `get()` for every"
                    )
                    appendLine(
                        "constructor parameter and ignores Kotlin defaults; if the missing parameter is a"
                    )
                    appendLine(
                        "test seam with a default, register the class via `single { Foo(arg = get()) }`"
                    )
                    appendLine(
                        "(NOT `singleOf(::Foo)`) so the default applies."
                    )
                    appendLine()
                    failures.forEach { appendLine(it) }
                }
            )
        }
    }

    private fun flatten(module: Module): Set<Module> {
        val result = mutableSetOf(module)
        module.includedModules.forEach { result += flatten(it) }
        return result
    }

    /**
     * Koin's `singleOf` / `viewModelOf` / `factoryOf` generate wrapper lambdas
     * via inlined extension functions; their synthetic class names contain
     * `$$inlined$...$default$`. User-provided `single { ... }` / `viewModel { ... }`
     * lambdas show up as plain Java synthetic lambdas (`$$Lambda/...`).
     *
     * Only the former auto-resolve every constructor parameter via `get()`,
     * so only they can exhibit the singleOf-with-defaults bug.
     */
    private fun isAutoGeneratedKoinLambda(definition: Any): Boolean =
        "\$\$inlined\$" in definition.javaClass.name

    companion object {
        // Provided by `androidContext(this)` at startKoin time. Not registered
        // as a definition, so declare it as an extra resolvable type.
        private val EXTRA_TYPES = listOf(Context::class)
        private val EXTRA_TYPES_SET = EXTRA_TYPES.toSet()

        // ViewModels constructed with runtime navigation arguments via
        // `parametersOf(...)`. Each entry tells the verifier which types are
        // injected as parameters (not from the graph).
        private val PARAMETERIZED_INJECTIONS = listOf(
            definition<BookshelfViewModel>(String::class),
            definition<BookDetailViewModel>(String::class, String::class),
        )

        private val PER_CLASS_INJECTIONS: Map<KClass<*>, List<KClass<*>>> = mapOf(
            BookshelfViewModel::class to listOf(String::class),
            BookDetailViewModel::class to listOf(String::class, String::class),
        )
    }
}
